apiVersion: apps.intern.dev/v1alpha1
kind: HelloApp
metadata:
  labels:
    app.kubernetes.io/name: hello-operator
    app.kubernetes.io/managed-by: kustomize
  name: helloapp-sample
  namespace: intern-assessment
spec:
  message: "Bonjour Merkl, l'operateur fonctionne !"
  replicas: 3